const TABLE_HEADER_DATA = [
  { label: 'id', value: 'id' },
  { label: 'Payer', value: 'payer' },
  { label: 'Indication', value: 'indication' },
  { label: 'Subtype', value: 'subtype' },
  { label: 'Line', value: 'line' },
  { label: 'Regimen', value: 'regimen' },
  { label: 'Book + Coverage', value: 'bookCoverage' },
  { label: 'Project', value: 'project' },
]

const MOCK_DATA = [
  {
    id: 'aetna-1',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'Commercial',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-2',
    payer: 'BAetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'MAC Medical',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-3',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'Medical Mutual',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-4',
    payer: 'CAetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'VA Medical',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-5',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'Commercial',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-6',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'MAC Medical',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-7',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'Medical Mutual',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-8',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'VA Medical',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-9',
    payer: 'ZAetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'Commercial',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-10',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'MAC Medical',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-11',
    payer: 'FAetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'Medical Mutual',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-12',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'VA Medical',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-13',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'Commercial',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-14',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'MAC Medical',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-15',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'Medical Mutual',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-16',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'VA Medical',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-17',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'Commercial',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-18',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'MAC Medical',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-19',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'Medical Mutual',
    project: 'Daiichi Breast',
  },
  {
    id: 'aetna-20',
    payer: 'Aetna',
    indication: 'Breast Cancer',
    subtype: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    bookCoverage: 'VA Medical',
    project: 'Daiichi Breast',
  },
]

export { MOCK_DATA, TABLE_HEADER_DATA }
