const TABLE_HEADER_DATA = [
  { label: '_id', value: '_id' },
  { label: 'Payer', value: 'organization' },
  { label: 'Indication', value: 'indication' },
  { label: 'Subtype', value: 'population' },
  { label: 'Line', value: 'line' },
  { label: 'Regimen', value: 'regimen' },
  { label: 'book', value: 'book' },
  { label: 'coverage', value: 'coverage' },
  { label: 'Project', value: 'project.name' },
]

const MOCK_DATA = [
  {
    _id: 'aetna-1',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'Commercial',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-2',
    organization: 'BAetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'MAC',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-3',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'Medical',
    coverage: 'Mutual',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-4',
    organization: 'CAetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'VA',
    coverage: 'Coverage',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-5',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'Commercial',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-6',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'MAC',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-7',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'Medical',
    coverage: 'Mutual',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-8',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'VA',
    coverage: 'Coverage',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-9',
    organization: 'ZAetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'Commercial',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-10',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'MAC',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-11',
    organization: 'FAetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'Medical',
    coverage: 'Mutual',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-12',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'VA',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-13',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'Commercial',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-14',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'MAC',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-15',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'Medical',
    coverage: 'Mutual',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-16',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'VA',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-17',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'Commercial',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-18',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'MAC',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-19',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'Medical',
    coverage: 'Mutual',
    project: { name: 'Daiichi Breast' },
  },
  {
    _id: 'aetna-20',
    organization: 'Aetna',
    indication: 'Breast Cancer',
    population: 'HER2+',
    line: '1L+ Metastatic',
    regimen: 'Herceptin',
    book: 'VA',
    coverage: 'Medical',
    project: { name: 'Daiichi Breast' },
  },
]

export { MOCK_DATA, TABLE_HEADER_DATA }
