version: "3.8"
   
services:
  polaris_prod:
    image: ghcr.io/pulse-analytics/polaris:latest
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    ports:
      - "1337:1337"
    restart: always
    container_name: polaris_prod
