module.exports = [
  {
    category: "Product Category",
    characteristic: "Product Char 1",
    categoryId: 1,
    characteristicId: 1,
    product: "Prod A Generic",
    productId: 0,
  },
  {
    category: "Product Category",
    characteristic: "Product Char 2",
    categoryId: 1,
    characteristicId: 2,
    product: "Prod A Generic",
    productId: 0,
  },
  {
    category: "Product Category",
    characteristic: "Product Char 1",
    categoryId: 1,
    characteristicId: 1,
    product: "Prod B Generic",
    productId: 1,
  },
  {
    category: "Product Category",
    characteristic: "Product Char 2",
    categoryId: 1,
    characteristicId: 2,
    product: "Prod B Generic",
    productId: 1,
  },
  {
    category: "Regimen Category",
    characteristic: "Regimen Char 1",
    categoryId: 2,
    characteristicId: 3,
    regimen: "Regimen A",
    regimenId: 0,
  },
  {
    category: "Regimen Category",
    characteristic: "Regimen Char 2",
    categoryId: 2,
    characteristicId: 4,
    regimen: "Regimen A",
    regimenId: 0,
  },
  {
    category: "Regimen Category",
    characteristic: "Regimen Char 1",
    categoryId: 2,
    characteristicId: 3,
    regimen: "Regimen B",
    regimenId: 1,
  },
  {
    category: "Regimen Category",
    characteristic: "Regimen Char 2",
    categoryId: 2,
    characteristicId: 4,
    regimen: "Regimen B",
    regimenId: 1,
  },
  {
    category: "Manufacturer Category",
    characteristic: "Manufacturer Char 1",
    categoryId: 3,
    characteristicId: 5,
    manufacturerId: 0,
    manufacturer: "Manufacturer A",
  },
  {
    category: "Manufacturer Category",
    characteristic: "Manufacturer Char 2",
    categoryId: 3,
    characteristicId: 6,
    manufacturerId: 0,
    manufacturer: "Manufacturer A",
  },
  {
    category: "Manufacturer Category",
    characteristic: "Manufacturer Char 1",
    categoryId: 3,
    characteristicId: 5,
    manufacturerId: 1,
    manufacturer: "Manufacturer B",
  },
  {
    category: "Manufacturer Category",
    characteristic: "Manufacturer Char 2",
    categoryId: 3,
    characteristicId: 6,
    manufacturerId: 1,
    manufacturer: "Manufacturer B",
  },
]
